"""
conftest.py — Shared pytest fixtures for Snowflake integration tests.

These tests run AFTER `make dbt-run` has populated the dev schemas.
They connect directly to Snowflake and query the materialized tables,
so they test the actual output rather than mocking anything.

Required environment variables (same as for dbt):
    SNOWFLAKE_ACCOUNT, SNOWFLAKE_USER, SNOWFLAKE_PASSWORD
Optional:
    SNOWFLAKE_ROLE (default: SYSADMIN)
    DBT_TARGET    (default: dev)

Usage:
    make pytest              # runs all tests in tests_pytest/
    pytest tests_pytest/ -v  # verbose output
    pytest tests_pytest/test_marts.py -v  # single module
"""

import json
import os
from pathlib import Path

import pytest

from utils.snowflake_loader import get_connection


# ---------------------------------------------------------------------------
# Session-scoped Snowflake connection
# Reusing one connection across the full test session avoids connection
# overhead on every test.  Session scope means: created once, torn down once.
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def snowflake_conn():
    """
    Open a Snowflake connection to the dev database for the test session.
    Yields the connection so it is properly closed even if tests fail.
    """
    target = os.environ.get("DBT_TARGET", "dev")
    database = "NYC_TAXI" if target == "dev" else "NYC_TAXI_PROD"

    conn = get_connection(database=database, schema="RAW")
    yield conn
    conn.close()


@pytest.fixture(scope="session")
def dev_staging_schema():
    target = os.environ.get("DBT_TARGET", "dev")
    return "DEV_STAGING" if target == "dev" else "STAGING"


@pytest.fixture(scope="session")
def dev_marts_core_schema():
    target = os.environ.get("DBT_TARGET", "dev")
    return "DEV_MARTS_CORE" if target == "dev" else "MARTS_CORE"


@pytest.fixture(scope="session")
def dev_marts_finance_schema():
    target = os.environ.get("DBT_TARGET", "dev")
    return "DEV_MARTS_FINANCE" if target == "dev" else "MARTS_FINANCE"


# ---------------------------------------------------------------------------
# dbt manifest loader
# After `dbt docs generate`, dbt writes target/manifest.json — a complete
# machine-readable description of every model, test, source, and macro.
# Tests can introspect the manifest to validate model metadata programmatically.
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def dbt_manifest():
    """
    Load and return the parsed dbt manifest.json.

    The manifest is generated by `dbt docs generate` (or any `dbt run`).
    If it doesn't exist, the fixture raises a clear error rather than failing
    silently with a confusing KeyError later.
    """
    manifest_path = Path(__file__).parent.parent / "target" / "manifest.json"
    if not manifest_path.exists():
        pytest.skip(
            f"manifest.json not found at {manifest_path}. "
            "Run `dbt run` or `dbt docs generate` first."
        )
    with open(manifest_path) as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Helper: run a SQL query and return all rows as a list of dicts
# ---------------------------------------------------------------------------


def query(conn, sql):
    """Execute SQL and return results as a list of dicts (column_name → value)."""
    with conn.cursor() as cur:
        cur.execute(sql)
        columns = [col[0].lower() for col in cur.description]
        return [dict(zip(columns, row)) for row in cur.fetchall()]
